//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLocalGovt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlutaEntities : DbContext
    {
        public AlutaEntities()
            : base("name=AlutaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<LG> LGs { get; set; }
        public virtual DbSet<PetitionCategory> PetitionCategories { get; set; }
        public virtual DbSet<PetitionComplaint> PetitionComplaints { get; set; }
        public virtual DbSet<PetitionInfo> PetitionInfoes { get; set; }
        public virtual DbSet<PetitionSignature> PetitionSignatures { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<UsersInfo> UsersInfoes { get; set; }
        public virtual DbSet<School> Schools { get; set; }
    }
}
