//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLocalGovt
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetitionComplaint
    {
        public int ComplaintId { get; set; }
        public string Complaint { get; set; }
    }
}
