//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLocalGovt
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetitionInfo
    {
        public int PetitionId { get; set; }
        public string Title { get; set; }
        public Nullable<int> StateId { get; set; }
        public string ToWhom { get; set; }
        public string WhySign { get; set; }
        public string Phone { get; set; }
        public int CategoryId { get; set; }
        public string NameOfFile { get; set; }
        public Nullable<int> ComplaintId { get; set; }
        public Nullable<System.DateTime> PetDate { get; set; }
        public Nullable<bool> Approval { get; set; }
        public string UserId { get; set; }
        public Nullable<int> LGId { get; set; }
        public Nullable<int> SchoolId { get; set; }
    }
}
