//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLocalGovt
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetitionSignature
    {
        public int SignId { get; set; }
        public string SignFirstName { get; set; }
        public string SignLastName { get; set; }
        public string SignEmail { get; set; }
        public string SignAdd { get; set; }
        public string SignCountry { get; set; }
        public string SignState { get; set; }
        public string SignCity { get; set; }
        public string SignWord { get; set; }
        public Nullable<int> PetitionId { get; set; }
    }
}
