//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLocalGovt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int Id { get; set; }
        public string Post1 { get; set; }
        public Nullable<int> Likes { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
