//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLocalGovt
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersInfo
    {
        public int UserId { get; set; }
        public string Email { get; set; }
        public string Surname { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public Nullable<int> SchoolId { get; set; }
    }
}
